temp <- tempfile()
download.file('http://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip',temp)
all_data<-read.csv(unzip(temp),sep = ";",header = T,quote = "",na.strings='?')
unlink(temp)
my_data<-subset(all_data,Date=='1/2/2007' | Date=='2/2/2007')
my_data$dt<-strptime(paste(my_data$Date,my_data$Time),"%d/%m/%Y %T")
png('plot1.png',bg = "transparent")
hist(my_data$Global_active_power,col=2,main='Global Active Power',xlab='Global Active Power (kilowatts)')
dev.off()
